### ISSUE TITLE
Choosing the right connector

### ISSUE THREAD

**Issue by Kfrard** [paveldn/haier-esphome#41]
Hi, I would like to connect ESP32-for-Haier using JST connector, I found this model: https://www.aliexpress.com/item/1005006027334406.html
Which option will be suitable?
![obraz](https://github.com/paveldn/haier-esphome/assets/52238753/400db125-178d-46dc-b4a2-b097a5789436)

**Comment by paveldn** [comment]
Hi. connector is JST SM04B-GHS-TB (LF)(SN)
So I think it should be JST 1.25 4P

**Comment by paveldn** [comment]
@Kfrard 
You need to connect your ESP to AC. There are 3 potential ways:
1. Make a board with JST SM04B connector and use the original cable to connect it to the AC. You **can't** directly solder the JST connector to the Wemos board. You will need to make your own custom board for this. 
2. You can find a cable that can connect to the AC board, for example, this one  https://www.aliexpress.com/item/1005003374938897.html (4P version) Solder it to your ESP and use without additional cable.
3. Same as 2 but instead of finding cable you just cuir original cable and use its bottom part
I would say option 1 is to much trouble. I would suggest you use option 2.

**Comment by paveldn** [comment]
Never tried this one. Should be OK. The only thing I am not 100% sure is overheating. Some ESP32 models especially compact boards are heating a lot and inside the AC compartment there is no ventilation so they can give you problems. 
I am using this one https://shop.m5stack.com/products/m5stamp-c3-mate-with-pin-headers on 2 of my ACs. Never had problems with them. It is more expensive but quite solid and powerful. I was able to run the BT proxy and Hair AC climate on those boards with out any problems.

**Comment by paveldn** [comment]
I suppose issue can be closed
